name: secure_chat_app
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  encrypt: ^5.0.3
  local_auth: ^2.1.6 # مكتبة البصمة والوجه
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true
